---

- name: 'download archive'
  get_url:
    url: '{{hashicorp_repo}}/vault/{{vault_version}}/{{vault_target}}'
    dest: '{{hashicorp_dir_staging}}'
    timeout: '{{hashicorp_internet_timeout}}'
    validate_certs: false
  tags:
  - ct-vault

- name: 'expand archive'
  unarchive:
    src: '{{hashicorp_dir_staging}}/{{vault_target}}'
    dest: '{{hashicorp_dir_bin}}'
    copy: false
  become: true
  ignore_errors: '{{ansible_check_mode|bool}}'
  tags:
  - ct-vault

- name: 'push bash include'
  template:
    src: vault.sh.j2
    dest: /usr/local/etc/bash.d/vault.sh
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
  - ct-vault

- name: 'system account'
  user:
    name: vault
    comment: 'Vault system account'
    shell: /bin/nologin
    state: present
    system: true
  become: true
  tags:
  - ct-vault

- name: 'directories'
  file:
    state: directory
    path: '{{item.path}}'
    owner: '{{item.owner}}'
    group: '{{item.group}}'
    mode: '{{item.mode}}'
  loop: '{{vault_dirs}}'
  become: true
  tags:
  - ct-vault

- name: 'render config template'
  template:
    src: '{{vault_role}}.json.j2'
    dest: '{{vault_etc_dir}}/{{vault_role}}.json'
    owner: root
    group: root
    mode: '0644'
  notify: handler_restart_vault
  become: true
  tags:
  - ct-vault

- name: 'render systemd unit file'
  template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: '0644'
  register: reg_service
  become: true
  tags:
  - ct-vault

- name: 'set vault service to {{vault_state}}'
  systemd:
    name: vault
    state: '{{vault_state}}'
    enabled: true
    daemon_reload: '{{reg_service is changed}}'
  become: true
  tags:
  - ct-vault

# --------------------------------
...
