---

- name: 'download archive'
  get_url:
    url: '{{hashicorp_repo}}/vault/{{vault_version}}/{{vault_target}}'
    dest: '{{hashicorp_dir_staging}}'
    timeout: '{{hashicorp_internet_timeout}}'
    validate_certs: false
  tags:
  - ct-vault

- name: 'expand archive'
  unarchive:
    src: '{{hashicorp_dir_staging}}/{{vault_target}}'
    dest: '{{hashicorp_dir_bin}}'
    copy: false
  become: true
  ignore_errors: '{{ansible_check_mode|bool}}'
  tags:
  - ct-vault

- name: 'push bash include'
  template:
    src: vault.sh.j2
    dest: /usr/local/etc/bash.d/vault.sh
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
  - ct-vault
  - ct-vault-scripts

- name: 'push init-vault.sh'
  template:
    src: init-vault.sh.j2
    dest: /usr/local/bin/init-vault.sh
    owner: root
    group: root
    mode: 0700
  become: true
  tags:
  - ct-vault
  - ct-vault-scripts

- name: 'push unseal-vault.sh'
  template:
    src: unseal-vault.sh.j2
    dest: /usr/local/bin/unseal-vault.sh
    owner: root
    group: root
    mode: 0700
  become: true
  tags:
  - ct-vault
  - ct-vault-scripts

- name: 'add system account'
  user:
    name: vault
    comment: 'Vault system account'
    shell: /bin/nologin
    state: present
    system: true
  become: true
  tags:
  - ct-vault

- name: 'create directories'
  file:
    state: directory
    path: '{{item.path}}'
    owner: '{{item.owner}}'
    group: '{{item.group}}'
    mode: '{{item.mode}}'
  loop: '{{vault_dirs}}'
  become: true
  tags:
  - ct-vault

- name: 'render config template'
  template:
    src: '{{vault_role}}.json.j2'
    dest: '{{vault_etc_dir}}/{{vault_role}}.json'
    owner: root
    group: root
    mode: '0644'
  notify: handler_restart_vault
  become: true
  tags:
  - ct-vault
  - ct-vault-svc

- name: 'render systemd unit file'
  template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: '0644'
  register: reg_service
  become: true
  tags:
  - ct-vault
  - ct-vault-svc

- name: 'set vault service to {{vault_state}}'
  systemd:
    name: vault
    state: '{{vault_state}}'
    enabled: true
    daemon_reload: '{{reg_service is changed}}'
  become: true
  tags:
  - ct-vault
  - ct-vault-svc

- name: 'init'
  command: /usr/local/bin/init-vault.sh
  args:
    creates: /var/tmp/vault/keys
  when: vault_master
  register: reg_vault_init
  changed_when: reg_vault_init.rc != 99
  become: true
  tags:
  - ct-vault
  - ct-vault-postinstall

- name: 'fetch files (1/2)'
  fetch:
    src: /var/tmp/vault/keys
    dest: /var/tmp/vault-keys
    flat: true
  when: vault_master
  become: true
  tags:
  - ct-vault
  - ct-vault-postinstall

- name: 'fetch files (2/2)'
  fetch:
    src: /var/tmp/vault/token
    dest: /var/tmp/vault-token
    flat: true
  when: vault_master
  become: true
  tags:
  - ct-vault
  - ct-vault-postinstall

- name: 'push files'
  copy:
    src: /var/tmp/vault-keys
    dest: /var/tmp/vault/keys
    group: root
    mode: '0600'
    owner: root
  when: not vault_master
  become: true
  tags:
  - ct-vault
  - ct-vault-postinstall

- name: 'unseal'
  command: /usr/local/bin/unseal-vault.sh
  register: reg_vault_unseal
  become: true
  changed_when: reg_vault_unseal.rc != 99
  tags:
  - ct-vault
  - ct-vault-postinstall

- name: clean up
  file:
    state: absent
    path: '{{item}}'
  loop: ['/var/tmp/vault/keys', '/var/tmp/vault/token']
  become: true
  tags:
  - ct-vault
  - ct-vault-postinstall

# --------------------------------
...
