---

- name: 'download archive'
  get_url:
    url: '{{hashicorp_repo}}/vault/{{vault_version}}/{{vault_target}}'
    dest: '{{hashicorp_dir_staging}}'
    timeout: '{{hashicorp_internet_timeout}}'
    validate_certs: false
  tags: ct-vault

- name: 'expand archive'
  unarchive:
    src: '{{hashicorp_dir_staging}}/{{vault_target}}'
    dest: '{{hashicorp_dir_bin}}'
    copy: false
  become: true
  ignore_errors: '{{ansible_check_mode|bool}}'
  tags: ct-vault

- name: 'push bash include'
  template:
    src: vault.sh.j2
    dest: /usr/local/etc/bash.d/vault.sh
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
  - ct-vault
  - ct-vault-scripts

- name: 'push init-vault.sh'
  template:
    src: init-vault.sh.j2
    dest: /usr/local/bin/init-vault.sh
    owner: root
    group: root
    mode: 0700
  when: vault_role == 'server'
  become: true
  tags:
  - ct-vault
  - ct-vault-scripts

- name: 'push Nomad server policy'
  copy:
    src: policy-nomad-server.hcl
    dest: /usr/local/etc
    owner: root
    group: root
    mode: 0644
  when: vault_role == 'server'
  become: true
  tags: ct-vault

- name: 'push unseal-vault.sh'
  template:
    src: unseal-vault.sh.j2
    dest: /usr/local/bin/unseal-vault.sh
    owner: root
    group: root
    mode: 0700
  when: vault_role == 'server'
  become: true
  tags:
  - ct-vault
  - ct-vault-scripts

- name: 'add system account'
  user:
    name: vault
    comment: 'Vault system account'
    shell: /bin/nologin
    state: present
    system: true
  become: true
  tags: ct-vault

- name: 'create directories'
  file:
    state: directory
    path: '{{item.path}}'
    owner: '{{item.owner}}'
    group: '{{item.group}}'
    mode: '{{item.mode}}'
  loop: '{{vault_dirs}}'
  become: true
  tags: ct-vault

- name: 'render config template'
  template:
    src: '{{vault_role}}.json.j2'
    dest: '{{vault_etc_dir}}/{{vault_role}}.json'
    owner: root
    group: root
    mode: '0644'
  notify: handler_reload_vault
  become: true
  tags:
  - ct-vault
  - ct-vault-svc

- name: 'render systemd unit file'
  template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault-{{vault_role}}.service
    owner: root
    group: root
    mode: '0644'
  register: reg_service
  become: true
  tags:
  - ct-vault
  - ct-vault-svc

- name: 'set Vault {{vault_role}} service to {{vault_state}}'
  systemd:
    name: vault-{{vault_role}}
    state: '{{vault_state}}'
    enabled: true
    daemon_reload: '{{reg_service is changed}}'
  become: true
  tags:
  - ct-vault
  - ct-vault-svc

# --------------------------------
...
