---
# --------------------------------

- name: "Install required packages"
  ansible.builtin.apt:
    name: "{{ vault_dependent_pkgs.debian }}"
    state: present
  become: true
  tags: [ct-vault]

# --------------------------------
...
