---
# --------------------------------

- name: "Install required packages"
  ansible.builtin.yum:
    name: "{{ vault_dependent_pkgs.redhat }}"
    state: present
  become: true
  tags: [ct-vault]

# --------------------------------
...
