---
- name: 'handler_reload_vault'
  ansible.builtin.systemd:
    state: reloaded
    name: vault-{{vault_role}}.service
  become: true

- name: 'handler_restart_vault'
  ansible.builtin.systemd:
    state: restarted
    name: vault-{{vault_role}}.service
  become: true
...
